version: '3'
services:
  ansiblehost1:
    image: httpd:latest
    ports:
      - "80:80"
    networks:
      app_net:
        ipv4_address: 192.0.2.50

  ansiblehost2:
    image: httpd:latest
    ports:
      - "443:443"
    networks:
      app_net:
        ipv4_address: 192.0.2.51

  ansiblehost3:
    image: httpd:latest
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: 192.0.2.52

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.0.2.0/24